# Generated by Django 5.1.6 on 2025-02-06 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_parent_comment_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookmark',
            new_name='Scrap',
        ),
        migrations.AlterField(
            model_name='scrap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.user'),
        ),
        migrations.AlterModelTable(
            name='scrap',
            table='scraps',
        ),
    ]
