# Generated by Django 5.1.5 on 2025-02-10 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_postlike_post_alter_postlike_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Scrap',
        ),
        migrations.DeleteModel(
            name='Tip',
        ),
    ]